import{a as b,S as w,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const S="https://pixabay.com/api/",v="50342866-da1b32c712fb25d761b3cb22e";async function q(e,o=1){try{const i={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await b.get(S,{params:i})).data}catch(i){throw console.error("Error fetching images:",i),i}}const d=document.querySelector(".gallery"),f=document.querySelector(".loader");document.querySelector(".load-more");const P=new w(".gallery a",{captionsData:"alt",captionDelay:250});function B(e){const o=e.map(({webformatURL:i,largeImageURL:n,tags:t,likes:r,views:s,comments:y,downloads:L})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${i}" alt="${t}" />
      </a>
      <div>
        <ul class="info">
          <li class="info-item"><h4>Likes:</h4><p>${r}</p></li>
          <li class="info-item"><h4>Views:</h4><p>${s}</p></li>
          <li class="info-item"><h4>Comments:</h4><p>${y}</p></li>
          <li class="info-item"><h4>Downloads:</h4><p>${L}</p></li>
        </ul>
      </div>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",o),P.refresh()}function M(){d.innerHTML=""}function E(){f.classList.add("is-visible")}function $(){f.classList.remove("is-visible")}function I(){const e=document.querySelector(".load-more");e&&e.classList.remove("is-hidden")}function m(){const e=document.querySelector(".load-more");e&&e.classList.add("is-hidden")}const h=document.querySelector(".form"),O=h.elements["search-text"],R=document.querySelector(".load-more");let p="",c=1,l=0,u=0;h.addEventListener("submit",x);R.addEventListener("click",C);function x(e){e.preventDefault();const o=O.value.trim();if(!o){a.warning({message:"Please enter a search term.",position:"topRight"});return}p=o,c=1,u=0,M(),m(),g()}function C(){c+=1,g(!0)}async function g(e=!1){E();try{const o=await q(p,c),{hits:i,totalHits:n}=o;if(u=n,l=l||i.length,i.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3});return}B(i),c*l<u?I():(m(),e&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})),e&&H()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{$()}}function H(){const e=document.querySelector(".gallery").firstElementChild;if(!e)return;const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
