import{a as L,S as b,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",v="50342866-da1b32c712fb25d761b3cb22e";async function w(t,o=1){try{const i={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await L.get(S,{params:i})).data}catch(i){throw console.error("Error fetching images:",i),i}}const d=document.querySelector(".gallery"),f=document.querySelector(".loader");document.querySelector(".load-more");const q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function B(t){const o=t.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:s,comments:g,downloads:y})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${i}" alt="${e}" />
      </a>
      <div>
        <ul class="info">
          <li class="info-item"><h4>Likes:</h4><p>${r}</p></li>
          <li class="info-item"><h4>Views:</h4><p>${s}</p></li>
          <li class="info-item"><h4>Comments:</h4><p>${g}</p></li>
          <li class="info-item"><h4>Downloads:</h4><p>${y}</p></li>
        </ul>
      </div>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",o),q.refresh()}function P(){d.innerHTML=""}function M(){f.classList.add("is-visible")}function E(){f.classList.remove("is-visible")}function $(){const t=document.querySelector(".load-more");t&&t.classList.remove("is-hidden")}function l(){const t=document.querySelector(".load-more");t&&t.classList.add("is-hidden")}const m=document.querySelector(".form"),O=m.elements["search-text"],R=document.querySelector(".load-more");let h="",c=1,u=0;m.addEventListener("submit",x);R.addEventListener("click",C);function x(t){t.preventDefault();const o=O.value.trim();if(!o){a.warning({message:"Please enter a search term.",position:"topRight"});return}h=o,c=1,u=0,P(),l(),p()}function C(){c+=1,p(!0)}async function p(t=!1){M();const o=15;try{const i=await w(h,c),{hits:n,totalHits:e}=i;if(u=e,n.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),l();return}B(n),n.length<o||c*o>=u?(l(),t&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})):$(),t&&H()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{E()}}function H(){const t=document.querySelector(".gallery").firstElementChild;if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
